modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/syntacticsplenda/adventurepack/issues"
authors="SyntacticSplenda"
license="MIT"

[[mods]]
modId="adventurepack"
version="1.16.1-1.0"
displayName="Adventure Tools"
description='''
Adds adventure themed items aimed at making the game less tedious.
'''
